name: 🏗️ CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'app_python/**'  # 🎯 Run only if changes occur in app_python/
  pull_request:
    branches:
      - main
    paths:
      - 'app_python/**'  # 🎯 Run only if PR modifies app_python/

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python/

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🏎️ Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          cache: "pip"  # Native caching for Python dependencies

      - name: 📦 Install dependencies
        run: pip install .  # Install from pyproject.toml

      - name: 🔍 Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."  # Linting without fixing

      - name: 🎨 Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"  # Ensure code is correctly formatted

      - name: 🧪 Run Tests with Pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true  # 🏆 Enable emojis in test output
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: '📝 Test Report'

  docker:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: app_python/

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build & Push Docker image
        run: |
          docker build -t moscow-time-webapp .
          docker tag moscow-time-webapp ${{ secrets.DOCKER_USERNAME }}/moscow-time-webapp
          docker push ${{ secrets.DOCKER_USERNAME }}/moscow-time-webapp

  security:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      security-events: write
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔍 Run Snyk Security Scan
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test app_python -sarif-file-output=snyk.sarif

      - name: 📤 Upload Snyk SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif